### ISSUE TITLE
Enforce environment variables which are required and have a type.

### ISSUE THREAD

**Issue by judepereira** [asyncy/platform-engine#149]
For example, the following may be specified in the `microservice.yml`:
```yaml
environment:
  BOT_TOKEN:
    required: true
    type: string
```
