### ISSUE TITLE
WIP Decorators spec

### ISSUE THREAD

**Issue by stevepeak** [asyncy/platform-engine#229]
**Decorators**, inspired by [Python Decorators](https://hackernoon.com/decorators-in-python-8fd0dce93c08), are functions that are called before the proceeding line. This enables Storyscript to have complex and async logic scoped and highly readable.

### Design Concepts

```coffee
function @first key:int
   # ...

@first()
@second(key:1)
service action key:2
```

1. Follow [Storyscript function design](https://github.com/storyscript/storyscript/issues/596)
1. Called in a linear order: Resolve arguments -> first -> second -> service action

### Questions
1. How/can you pass arguments to the Decorator (like how Python does it)? *TBD*
1. Are the arguments for `service action` resolved first before `@first()` is called? **Yes**, IMO they must be.
1. Should the Decorator `return` be an adjusted data set?
1. Can Decorator change the data during the function?
1. Can a Decorator throw a "stop execution" indication?

### Example Decorators
<details>
<summary><code>@ratelimit(limit:1000 reset:1h)</code> (click to see <code>microservice.yml</code>)</summary>

```yaml
type: function
arguments:
    limit:
        help: Number of executions allowed
        type: int
        range:
            min: 1
        required: true
    reset:
        type: int
        help: How many seconds till the the limit is reset
        range:
            min: 0
    throttle:
        help: |
            How many executions per interval may be ran.
            If exceeded, the execution will be blocked (or retried).
        type: int
        range:
            min: 1
    interval:
        help: |
            How many executions may run during this interval of time
            Required when using throttle.
        type: int
        range:
            min: 1
    retry:
        type: boolean
        help: When the execution is blocked retry it after the next reset
        default: false
    call_when_blocked:
        type: function
        help: |
            Call this method when an execution is blocked
            Only used if retry is false
```

</details>

### Related issues
- [Storyscript Annotations](https://github.com/storyscript/storyscript/issues/390) are not Decorators, but worth mentioning here.
